# Generated by Django 4.2.7 on 2024-04-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0002_contactlist_phone_no_contactlist_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
